### ISSUE TITLE
return dimensions of spatial_rate_map

### ISSUE THREAD

**Issue by tristanstoeber** [CINPLA/expipe#5] opened 2017-02-17 15:35 UTC
What is the reason that the return dimension of the spatial rate map is:
 [box_ylen/binsize - 1, box_xlen/binsize -1] ?

I guess the issue is in line 64 of  expipe/expipe/analysis/tracking/fields.py:

```
# correct for shifting of map since digitize returns values at right edges
# and a supplemental bin added in L 55-56
spike_pos = spike_pos[1:-1, 1:-1]
```

Assume that my binsize is 0.1m and the box is a square of 1m, shouldnt it be natural that the rate map has the dimension is [10, 10] and not [9, 9]?

I can fix it, but as this may be my first contribution to expipe I better ask first.

**Comment by lepmik** [comment] 2017-02-18 12:43
Hi, thanks for writing the issue. I did not finish this code completely
while working on it earlier, I will fix it later today if that's alright.

17. feb. 2017 15.35 skrev "Tristan Stöber" <notifications@github.com>:

What is the reason that the return dimension of the spatial rate map is:
[box_ylen/binsize - 1, box_xlen/binsize -1] ?

I guess the issue is in line 64 of expipe/expipe/analysis/
tracking/fields.py:

`# correct for shifting of map since digitize returns values at right edges
and a supplemental bin added in L 55-56

spike_pos = spike_pos[1:-1, 1:-1]`

Assume that my binsize is 0.1m and the box is a square of 1m, shouldnt it
be natural that the rate map has the dimension is [10, 10] and not [9, 9]?

I can fix it, but as this may be my first contribution to expipe I better
ask first.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CINPLA/expipe/issues/5>, or mute the thread

**Comment by lepmik** [comment] 2017-02-18 18:47
Fixed in https://github.com/CINPLA/expipe/commit/8a5155b9c38eae8e45c9a5c2a279f38c6763964f

**Closed by lepmik** 2017-02-18 18:47 UTC

**Comment by tristanstoeber** [comment] 2017-02-20 16:28
cheers mikkel!
